### ISSUE TITLE
Finalize specs for payload

### ISSUE THREAD

**Issue by aaomidi** [Zyncco/Specs#1]
Finalize the specs we're going to use for the servers.

**Comment by aaomidi** [comment]
Please update the specs with any new features added @Vilsol @mkotb

**Comment by aaomidi** [comment]
My opinion on how we should handle encryption model:

- Make sure you specify UTF-8 for the data that's being encrypted
- `AES/GCM/NoPadding` For the encryption model itself, with this encryption model we wouldn't need a hash. (https://crypto.stackexchange.com/questions/2310/what-is-the-difference-between-cbc-and-gcm-mode)
- `SecureRandom` should be defined locally every time we need to use it (Not a member of the global class).
- Base64 the output

**Comment by aaomidi** [comment]
This is also a good thing to take a look at https://developers.google.com/protocol-buffers/

**Comment by aaomidi** [comment]
For the chrome extension, you can use https://crypto.stanford.edu/sjcl/

**Comment by devmattrick** [comment]
@aaomidi why use SJCL over the native Web Crypto API?

https://www.w3.org/TR/WebCryptoAPI/
https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API
https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API/Supported_algorithms

**Comment by aaomidi** [comment]
This seems like it would work better! Thanks matt!

**Comment by BranicYeti** [comment]
If we want to use AES, we can't use Web Crypto. The only algorithm(s) it supports with a user password is PBKDF2. See [here](https://github.com/diafygi/webcrypto-examples/blob/master/index.html#L1367-L1369). AES creates a CryptoKey object to be used with the encrypt function. See [here](https://github.com/diafygi/webcrypto-examples/blob/master/index.html#L111-L113).

**Comment by aaomidi** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/importKey Doesn't this allow import?

It wouldn't make sense for them to only allow generation, you need to decrypt too.

Excuse the accidental close

**Comment by BranicYeti** [comment]
Scratch that, I wasn't looking in the right place

**Comment by BranicYeti** [comment]
Okay. In Web Crypto API:
- Import raw PBKDF2 key with `password` as ArrayBuffer (use: deriveKey)
- Derive AES-GCM key from PBKDF2 key, using `SHA-1` to hash and a random salt (use: encrypt, decrypt)
- Encrypt `data` as ArrayBuffer with AES-GCM key, using random `iv`
- Decrypt `data` as ArrayBuffer with AES-GCM key, using same `iv` as used when encrypting

As a result of these findings, I believe we need to include the `salt` and the `iv` in the payload with the encrypted data, since it will need to persist, at least between JavaScript clients. Unsure how it'll work within Android and others.

**Comment by jercos** [comment]
You'll need to send the IV with the encrypted payload every time anyway, and using a timestamp creates a sequential pattern that any CTR-related mode (like GCM) is potentially weakened by. So you can... use a good random IV and have no issues, or arbitrarily decide not to use a good random IV and create a potential security issue for no visible gain? I don't get your reasoning.

As to salting the key, PBDKF2 (and any other reasonable other KDF) already takes a cryptographic salt, and outputs a fixed-length bitstring. My advice would be to make that salt random too, and use the output of PBKDF2 directly as a key. I don't know of any potential weakness arising from using the same random value as both the encryption IV and KDF salt if you're just trying to squeeze bits out of your message size for some reason, so long as a new random value is generated for each encryption.

Use of a random salt for the KDF invalidates the idea of only keeping the AES-GCM key locally, since a new key would be used for each message, however the passphrase would need to be held/re-entered for decryption either way... unless of course you're allowing the server to choose the salt?

**Comment by BranicYeti** [comment]
@jercos Don't take this the wrong way, I'm asking out of curiosity rather than passive aggressive confrontation. What do you know about cryptography and secure transfer of encrypted data?

**Comment by jercos** [comment]
@BranicYeti I'd describe myself as a hobbyist. Probably just enough to get myself into trouble. ;)

**Comment by aaomidi** [comment]
You can transfer the IV over the Internet in plain text without an issue.

**Comment by mkotb** [comment]
One thing we need to keep in mind is that SecretKeyFactory with AES only
supports Android versions 23+ and our min version is 21. Therefore we
wouldn't be able to use the built in PBDFK and I'm not interested in
rolling out our own crypto.

**Comment by aaomidi** [comment]
@BranicYeti about your comment earlier on `iv`s and `salts`. @jercos is, I think, right when he says we can use the same "`salt`, as in bits of randomness" for salting the password and for using it as the `iv`. However, there isn't anything blocking us from generating a new salt every time an encryption occurs.

So basically with every payload, we include the `salt` and `iv` that was used in generating the encrypted output.

**Comment by aaomidi** [comment]
@mkotb https://search.maven.org/#search|ga|1|g:com.madgag.spongycastle For PBDFK2

**Comment by BranicYeti** [comment]
@jercos In that case, thank you for your input. You probably saved an hour long debate in Slack over how we were going to do that. Assuming we are in fact sticking with AES-GCM, that will be a huge favour to us.

**Comment by jercos** [comment]
@mkotb My experience with Java APIs is pretty minimal, but I believe the `SecretKeyFactory` you need would be `PBKDF2WithHmacSHA1`, not `AES`. The resulting `SecretKey` can then be directly used to create a `SecretKeySpec` with the `AES` algorithm.

**Comment by mkotb** [comment]
@jercos Yep, I had seemed to have figured it out.

## Encryption
Right now I use PBKDF2withHmacSHA1 with a random salt and IV, both are sent over plaintext in the payload and AES/GCM/NoPadding with an authenticated tag length of 128. The implemented code is [here](https://github.com/Zyncco/Android-App/blob/b150022e2982cab3886814403e9fa862337c3b1f/app/src/main/java/co/zync/zync/utils/ZyncCrypto.java#L23-L34) and [here](https://github.com/Zyncco/Android-App/blob/b150022e2982cab3886814403e9fa862337c3b1f/app/src/main/java/co/zync/zync/api/ZyncClipData.java#L27-L35). This is implemented and working on the Android App. 

## Added Fields

`iv` and `salt` fields have been added to align with the cryptographic method. 

Hopefully, this is warranted for an update to the Spec repository and a closing of this issue.

Waiting on a sign off from @aaomidi @Vilsol and @BranicYeti

**Comment by aaomidi** [comment]
As long as the PBKDF2 algorithm is alright, I think this is the proper way of doing it.
